[package]
name = "solo5"
version = "0.1.0"
authors = ["Nikita Nazarenko <savant.d@gmail.com>"]
publish = false

[features]
ukvm = []
virtio = []

[dependencies]
rlibc="1.0"
volatile = "0.1.0"
spin = "0.4"
wee_alloc={git="https://github.com/savant2212/wee_alloc", features=["ptr_array_backend"]}
